apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - name: reservations
        image: northamerica-northeast2-docker.pkg.dev/modern-impulse-448721-t3/fastapi-docker-repo/reservations:v5
        ports:
        - containerPort: 8004