apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-authentication
  template:
    metadata:
      labels:
        app: customer-authentication
    spec:
      containers:
      - name: customer-authentication
        image: northamerica-northeast2-docker.pkg.dev/modern-impulse-448721-t3/fastapi-docker-repo/customer_auth:v1
        ports:
        - containerPort: 8001