version: '3.8'

services:
  customer-authentication:
    build:
      context: ./customer-authentication
      dockerfile: Dockerfile
    container_name: customer-authentication
    ports:
      - "8000:8000"
    volumes:
      - ./customer-authentication:/app  # remove this section later
    environment:
      - CATALOG_SERVICE_URL=http://catalog:8000/catalog
    depends_on:
      - catalog

  catalog:
    build:
      context: ./catalog
      dockerfile: Dockerfile
    container_name: catalog
    ports:
      - "8000:8000"
    volumes:
      - ./catalog:/app  # remove this section later
