apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylibrary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mylibrary
  template:
    metadata:
      labels:
        app: mylibrary
    spec:
      containers:
      - name: mylibrary
<<<<<<< HEAD
        image: northamerica-northeast2-docker.pkg.dev/lms-capstone-456217/fastapi-docker-repo/mylibrary:v2
=======
        image: northamerica-northeast2-docker.pkg.dev/lms-capstone-456217/fastapi-docker-repo/mylibrary:v1
>>>>>>> d07a66a14e1e62e634f069590dc93bde8a7b5b00
        ports:
        - containerPort: 8005